# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.define "jenkins" do |jenkins|
    jenkins.vm.box ="ubuntu/xenial64"
      jenkins.vm.network "private_network", ip: "192.0.0.71"
      jenkins.vm.provision "shell", path: "jenkins.sh"
          jenkins.vm.provider "virtualbox" do |vb|
            vb.gui = true
              ### Change network card to PCnet-FAST III
              # For NAM`M`T adapter
              #vb.customize ["modifyvm", :id, "--nictype1", "Am79C973"]
              # For host-only adapter
              #vb.customize ["modifyvm", :id, "--nictype2", "Am79C973"]
          #
          #   # Customize the amount of memory on the VM:
             vb.memory = "4096"
          end
    end
  
end
